management:
  tracing:
    sampling:
      probability: 1.0  # 모든 트래픽 추적
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

spring:
  application:
    name: payment-gateway
  cloud:
    gateway:
      routes:
        - id: payment-service-route
          uri: http://payment-service:8081      # 실제 결제 서비스 주소
          predicates:
            - Path=/v1/payments/** # 이 경로로 들어오면
          filters:
            - name: RequestRateLimiter     # 호출 제한 필터 적용
              args:
                replenishRate: 10
                burstCapacity: 20
                # 어떤 키로 제한할지 (사용자 IP 등) 설정
                key-resolver: "#{@ipKeyResolver}"

  data:
    redis:
      # 도커 환경변수가 없을 때를 대비한 기본값
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true # Actuator
        slidingWindowSize: 10         # 최근 10개의 요청을 기준
        failureRateThreshold: 50      # 실패율 50% 이상 시 서킷 OPEN
        waitDurationInOpenState: 10s  # OPEN 후 10초 뒤에 HALF_OPEN으로 변경
        permittedNumberOfCallsInHalfOpenState: 3 # HALF_OPEN 상태에서 시도할 횟수
    instances:
      pgService:
        baseConfig: default
  retry:
    instances:
      pgService:
        maxAttempts: 3                # 최대 3번 시도
        waitDuration: 500ms           # 재시도 간격